"use client";

import { FormEvent, useState } from "react";
import { Braces, Check, Clipboard, FilePenLine, HelpCircle, Layers3, LoaderCircle, WandSparkles } from "lucide-react";
import { Badge, Button, Card, PageHeader } from "@/components/ui";

type Action = "rewrite" | "intro" | "faq" | "entity";
const tabs: { id: Action; label: string; description: string; icon: typeof FilePenLine }[] = [
  { id: "rewrite", label: "리라이팅", description: "5가지 패턴", icon: FilePenLine },
  { id: "intro", label: "도입부", description: "3단 공식", icon: Layers3 },
  { id: "faq", label: "FAQ", description: "+ JSON-LD", icon: HelpCircle },
  { id: "entity", label: "엔티티", description: "+ Organization", icon: Braces },
];
const patterns = ["형용사→수치", "일반→조건부", "나열→구조화", "대상 명시", "결론 선행"];
async function json<T>(response: Response): Promise<T> { const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error ?? "요청에 실패했습니다."); return data; }

export function StudioClient() {
  const [action, setAction] = useState<Action>("rewrite");
  const [text, setText] = useState(""); const [topic, setTopic] = useState("");
  const [selectedPatterns, setSelectedPatterns] = useState<string[]>(["결론 선행"]);
  const [entity, setEntity] = useState({ company: "", target: "", value: "", category: "", metric: "", url: "", logo: "", sameAs: "" });
  const [provider, setProvider] = useState<"openai" | "anthropic" | "gemini" | "grok">("openai");
  const [result, setResult] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);

  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); setResult(null); try { const data = await json<{ result: { output: Record<string, unknown> } }>(await fetch("/api/studio", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, text, topic, patterns: selectedPatterns, provider, ...entity, sameAs: entity.sameAs.split(",").map((item) => item.trim()).filter(Boolean) }) })); setResult(data.result.output); } catch (cause) { setError(cause instanceof Error ? cause.message : "생성에 실패했습니다."); } finally { setLoading(false); } }
  async function copy() { if (!result) return; await navigator.clipboard.writeText(JSON.stringify(result, null, 2)); setCopied(true); setTimeout(() => setCopied(false), 1500); }

  return <div><PageHeader eyebrow="Content lab" title="콘텐츠 스튜디오" description="AI가 인용하기 쉬운 구조로 고치고, 도입부·FAQ·엔티티와 구조화 데이터를 한 번에 만듭니다." />
    <div className="mb-5 grid grid-cols-2 gap-2 lg:grid-cols-4">{tabs.map(({ id, label, description, icon: Icon }) => <button type="button" key={id} onClick={() => { setAction(id); setResult(null); setError(""); }} className={`flex items-center gap-3 rounded-xl border p-3 text-left transition ${action === id ? "border-cyan-400/30 bg-cyan-400/10" : "border-white/7 bg-slate-900/50 hover:bg-white/5"}`}><span className={`grid h-9 w-9 place-items-center rounded-lg ${action === id ? "bg-cyan-400/15 text-cyan-300" : "bg-slate-800 text-slate-500"}`}><Icon className="h-4 w-4" /></span><span><strong className="block text-sm text-slate-200">{label}</strong><small className="text-[11px] text-slate-500">{description}</small></span></button>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><Card><form onSubmit={submit} className="space-y-4"><div className="flex items-center justify-between"><h2 className="font-semibold text-white">{tabs.find((tab) => tab.id === action)?.label} 입력</h2>{action !== "entity" && <select aria-label="LLM 제공자" className="w-auto text-xs" value={provider} onChange={(e) => setProvider(e.target.value as typeof provider)}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Gemini</option><option value="grok">Grok</option></select>}</div>
      {action === "rewrite" && <><label className="block text-sm">원문<textarea className="mt-2" rows={12} required value={text} onChange={(e) => setText(e.target.value)} placeholder="리라이팅할 콘텐츠를 붙여넣으세요." /></label><fieldset><legend className="mb-2 text-sm text-slate-300">적용 패턴</legend><div className="flex flex-wrap gap-2">{patterns.map((pattern) => <label key={pattern} className={`cursor-pointer rounded-lg border px-3 py-2 text-xs ${selectedPatterns.includes(pattern) ? "border-cyan-400/30 bg-cyan-400/10 text-cyan-300" : "border-white/8 text-slate-500"}`}><input className="sr-only" type="checkbox" checked={selectedPatterns.includes(pattern)} onChange={(e) => setSelectedPatterns((items) => e.target.checked ? [...items, pattern] : items.filter((item) => item !== pattern))} />{pattern}</label>)}</div></fieldset></>}
      {(action === "intro" || action === "faq") && <><label className="block text-sm">{action === "intro" ? "글의 주제" : "FAQ 주제 또는 자료"}<textarea className="mt-2" rows={12} required value={topic} onChange={(e) => setTopic(e.target.value)} placeholder={action === "intro" ? "독자와 핵심 주제를 설명하세요." : "고객 질문의 기반이 될 자료를 입력하세요."} /></label>{action === "intro" && <div className="grid grid-cols-3 gap-2">{["문제 제시", "핵심 답변", "글의 가치"].map((step, index) => <div key={step} className="rounded-lg bg-slate-950/50 p-2 text-center text-[11px] text-slate-500"><strong className="mr-1 text-cyan-400">{index + 1}</strong>{step}</div>)}</div>}</>}
      {action === "entity" && <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">회사명<input className="mt-2" required value={entity.company} onChange={(e) => setEntity((v) => ({ ...v, company: e.target.value }))} /></label><label className="text-sm">타깃 고객<input className="mt-2" required value={entity.target} onChange={(e) => setEntity((v) => ({ ...v, target: e.target.value }))} /></label><label className="text-sm">핵심 가치<input className="mt-2" required value={entity.value} onChange={(e) => setEntity((v) => ({ ...v, value: e.target.value }))} /></label><label className="text-sm">카테고리<input className="mt-2" required value={entity.category} onChange={(e) => setEntity((v) => ({ ...v, category: e.target.value }))} /></label><label className="text-sm">수치·성과 <span className="text-slate-600">(선택)</span><input className="mt-2" value={entity.metric} onChange={(e) => setEntity((v) => ({ ...v, metric: e.target.value }))} /></label><label className="text-sm">공식 URL <span className="text-slate-600">(선택)</span><input className="mt-2" type="url" value={entity.url} onChange={(e) => setEntity((v) => ({ ...v, url: e.target.value }))} /></label><label className="text-sm">로고 URL <span className="text-slate-600">(선택)</span><input className="mt-2" type="url" value={entity.logo} onChange={(e) => setEntity((v) => ({ ...v, logo: e.target.value }))} /></label><label className="text-sm">공식 프로필 sameAs <span className="text-slate-600">(쉼표 구분)</span><input className="mt-2" value={entity.sameAs} onChange={(e) => setEntity((v) => ({ ...v, sameAs: e.target.value }))} placeholder="https://linkedin.com/company/..." /></label></div>}
      <Button className="w-full" disabled={loading || (action === "rewrite" && !selectedPatterns.length)}>{loading ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <WandSparkles className="h-4 w-4" />}{loading ? "생성 중…" : action === "entity" ? "정의와 JSON-LD 생성" : "AI로 생성"}</Button>{error && <p role="alert" className="rounded-xl bg-rose-400/10 p-3 text-sm text-rose-300">{error}</p>}</form></Card>
      <Card className="min-h-[32rem]"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold text-white">결과</h2><p className="mt-1 text-xs text-slate-500">실행 결과는 로컬 이력에 저장됩니다.</p></div>{result && <Button type="button" variant="secondary" onClick={copy}>{copied ? <Check className="h-4 w-4" /> : <Clipboard className="h-4 w-4" />}{copied ? "복사됨" : "JSON 복사"}</Button>}</div>{result ? <div className="space-y-4">{"before" in result && <div className="rounded-xl border border-white/7 bg-slate-950/40 p-4"><Badge>Before</Badge><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-500">{String(result.before)}</p></div>}{"after" in result && <div className="rounded-xl border border-cyan-400/15 bg-cyan-400/[0.04] p-4"><Badge tone="cyan">After</Badge><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-200">{String(result.after)}</p></div>}{"intro" in result && <p className="whitespace-pre-wrap rounded-xl bg-slate-950/40 p-4 text-sm leading-7 text-slate-200">{String(result.intro)}</p>}{"definition" in result && <p className="rounded-xl border border-cyan-400/15 bg-cyan-400/5 p-4 text-base leading-7 text-cyan-100">{String(result.definition)}</p>}{"faqs" in result && <div className="space-y-3">{(result.faqs as { question: string; answer: string }[]).map((faq) => <details key={faq.question} className="rounded-xl border border-white/7 bg-slate-950/40 p-4"><summary className="cursor-pointer text-sm font-semibold text-slate-200">{faq.question}</summary><p className="mt-3 text-sm leading-6 text-slate-400">{faq.answer}</p></details>)}</div>}{"jsonLd" in result && <pre className="max-h-96 rounded-xl bg-slate-950 p-4 text-xs leading-5 text-emerald-300">{JSON.stringify(result.jsonLd, null, 2)}</pre>}</div> : <div className="grid min-h-96 place-items-center text-center"><div><WandSparkles className="mx-auto h-8 w-8 text-slate-700" /><p className="mt-3 text-sm text-slate-600">도구를 실행하면 전·후 비교와<br />구조화 데이터가 여기에 표시됩니다.</p></div></div>}</Card></div>
  </div>;
}
