"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Database, Download, FileUp, LoaderCircle, ShieldCheck } from "lucide-react";
import { Badge, Button, Card, EmptyState, PageHeader } from "@/components/ui";

interface Stats { projects: number; questionSets: number; questions: number; measureRuns: number; measureResults: number; audits: number; auditItems: number; contents: number; checklistStates: number; strategyItems: number }
interface Preview { kind?: string; schemaVersion?: number; exportedAt?: string; workspaceName?: string; stats?: Stats }
interface Summary { workspace: { schemaVersion: number; stats: Stats; apiKeysExcluded: boolean } }
const labels: Record<keyof Stats, string> = { projects: "프로젝트", questionSets: "질문 세트", questions: "질문", measureRuns: "측정", measureResults: "측정 응답", audits: "진단", auditItems: "진단 항목", contents: "콘텐츠 결과", checklistStates: "체크리스트", strategyItems: "전략 항목" };
async function json<T>(response: Response): Promise<T> { const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "요청에 실패했습니다."); return body; }

export function WorkspaceClient() {
  const [summary, setSummary] = useState<Summary["workspace"] | null>(null); const [snapshot, setSnapshot] = useState<unknown>(null); const [preview, setPreview] = useState<Preview | null>(null);
  const [fileName, setFileName] = useState(""); const [mode, setMode] = useState<"merge" | "replace">("merge"); const [confirmReplace, setConfirmReplace] = useState(false);
  const [loading, setLoading] = useState(true); const [importing, setImporting] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function refresh() { const data = await json<Summary>(await fetch("/api/workspace")); setSummary(data.workspace); }
  useEffect(() => { void (async () => { try { await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "현황을 불러오지 못했습니다."); } finally { setLoading(false); } })(); }, []);
  const total = useMemo(() => summary ? Object.values(summary.stats).reduce((sum, count) => sum + count, 0) : 0, [summary]);
  async function chooseFile(event: ChangeEvent<HTMLInputElement>) {
    setError(""); setMessage(""); setSnapshot(null); setPreview(null); const file = event.target.files?.[0]; if (!file) return; setFileName(file.name);
    if (file.size > 24 * 1024 * 1024) { setError("가져오기 파일은 24MB 이하여야 합니다."); return; }
    try { const parsed = JSON.parse(await file.text()) as Preview; if (parsed.kind !== "geo-master-workspace" || parsed.schemaVersion !== 1 || !parsed.stats) throw new Error("GEO Master 스키마 v1 파일이 아닙니다."); setSnapshot(parsed); setPreview(parsed); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "JSON 파일을 읽지 못했습니다."); }
  }
  async function importFile(event: FormEvent) {
    event.preventDefault(); if (!snapshot) return; setImporting(true); setError(""); setMessage("");
    try { const data = await json<{ result: { mode: string; idPolicy: string; apiKeysPreserved: boolean } }>(await fetch("/api/workspace", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode, confirmReplace, snapshot }) })); setMessage(`${data.result.mode === "merge" ? "병합" : "교체"} 가져오기가 완료되었습니다. API 키는 유지되었습니다.`); setSnapshot(null); setPreview(null); setFileName(""); setConfirmReplace(false); await refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "가져오기에 실패했습니다."); }
    finally { setImporting(false); }
  }
  return <div><PageHeader eyebrow="Portable workspace" title="팀 공유 스냅샷" description="업무 데이터를 버전된 JSON으로 옮깁니다. API 키·암호문·로컬 마스터 키는 내보내지 않으며 가져올 기기의 키를 그대로 유지합니다." action={<a href="/api/workspace?download=1" download className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-cyan-400 px-4 py-2 text-sm font-bold text-slate-950 hover:bg-cyan-300"><Download className="h-4 w-4" />JSON 내보내기</a>} />
    <div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><div className="space-y-5"><Card><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400/10"><Database className="h-5 w-5 text-cyan-300" /></span><div><h2 className="font-semibold text-white">현재 휴대 데이터</h2><p className="text-xs text-slate-500">총 {total.toLocaleString("ko-KR")}개 레코드 · schema v{summary?.schemaVersion ?? 1}</p></div></div>{loading ? <LoaderCircle className="mx-auto my-10 h-6 w-6 animate-spin text-cyan-400" /> : summary ? <div className="mt-5 grid grid-cols-2 gap-2">{(Object.keys(labels) as (keyof Stats)[]).map((key) => <div key={key} className="flex justify-between rounded-lg bg-slate-950/40 px-3 py-2 text-xs"><span className="text-slate-500">{labels[key]}</span><strong className="text-slate-300">{summary.stats[key]}</strong></div>)}</div> : <EmptyState>현황을 불러오지 못했습니다.</EmptyState>}<div className="mt-4 flex items-center gap-2 text-xs text-emerald-300"><ShieldCheck className="h-4 w-4" />API 키 및 암호화 열 제외</div></Card>
      <Card><h2 className="font-semibold text-white">ID 충돌 정책</h2><div className="mt-4 space-y-3 text-xs leading-5 text-slate-400"><p><Badge tone="cyan">병합</Badge> 기존 레코드는 유지하고 가져온 모든 기본 키를 새 ID로 재매핑합니다. 브랜드 프로필은 스냅샷 값으로 적용합니다.</p><p><Badge tone="warn">교체</Badge> 휴대 가능한 기존 데이터만 지운 뒤 스냅샷 ID를 보존합니다. 저장된 API 키는 삭제하지 않습니다.</p></div></Card></div>
      <Card><form onSubmit={importFile}><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-400/10"><FileUp className="h-5 w-5 text-violet-300" /></span><div><h2 className="font-semibold text-white">JSON 가져오기</h2><p className="text-xs text-slate-500">구조·버전·레코드 수·관계 무결성을 서버에서 다시 검증합니다.</p></div></div><label className="mt-5 flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-white/12 bg-slate-950/30 p-5 text-center hover:border-cyan-400/30"><FileUp className="h-6 w-6 text-slate-600" /><span className="mt-2 text-sm text-slate-300">{fileName || "GEO Master JSON 파일 선택"}</span><span className="mt-1 text-xs text-slate-600">최대 24MB</span><input className="sr-only" type="file" accept="application/json,.json" onChange={chooseFile} /></label>
      {preview && <div className="mt-4 rounded-xl border border-white/7 bg-slate-950/35 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold text-white">{preview.workspaceName || "이름 없는 워크스페이스"}</p><p className="mt-1 text-xs text-slate-500">schema v{preview.schemaVersion} · {preview.exportedAt ? new Date(preview.exportedAt).toLocaleString("ko-KR") : "날짜 없음"}</p></div><Badge tone="good">구조 확인</Badge></div>{preview.stats && <p className="mt-3 text-xs text-slate-400">{Object.values(preview.stats).reduce((sum, count) => sum + count, 0).toLocaleString("ko-KR")}개 레코드</p>}</div>}
      <fieldset className="mt-5"><legend className="text-sm font-semibold text-slate-300">가져오기 방식</legend><div className="mt-2 grid gap-2 sm:grid-cols-2"><label className={`rounded-xl border p-3 text-sm ${mode === "merge" ? "border-cyan-400/30 bg-cyan-400/5" : "border-white/7"}`}><input type="radio" name="mode" value="merge" checked={mode === "merge"} onChange={() => { setMode("merge"); setConfirmReplace(false); }} /> <span className="ml-2">기존 데이터와 병합</span></label><label className={`rounded-xl border p-3 text-sm ${mode === "replace" ? "border-rose-400/30 bg-rose-400/5" : "border-white/7"}`}><input type="radio" name="mode" value="replace" checked={mode === "replace"} onChange={() => setMode("replace")} /> <span className="ml-2">현재 데이터 교체</span></label></div></fieldset>
      {mode === "replace" && <label className="mt-4 flex items-start gap-2 rounded-xl border border-rose-400/20 bg-rose-400/5 p-3 text-xs leading-5 text-rose-200"><input className="mt-1" type="checkbox" checked={confirmReplace} onChange={(event) => setConfirmReplace(event.target.checked)} /><span><strong>교체를 이해했습니다.</strong><br />현재 프로젝트·측정·진단·콘텐츠·전략 데이터가 스냅샷으로 바뀝니다.</span></label>}
      <Button className="mt-5 w-full" disabled={!snapshot || importing || (mode === "replace" && !confirmReplace)}>{importing ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <FileUp className="h-4 w-4" />}{importing ? "검증 및 가져오는 중…" : "스냅샷 가져오기"}</Button></form>{error && <p role="alert" className="mt-4 flex gap-2 rounded-xl bg-rose-400/10 p-3 text-sm text-rose-300"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</p>}{message && <p aria-live="polite" className="mt-4 flex gap-2 rounded-xl bg-emerald-400/10 p-3 text-sm text-emerald-300"><CheckCircle2 className="h-4 w-4 shrink-0" />{message}</p>}</Card></div>
  </div>;
}
