// Ported from leecg39/GEO_master2 packages/core/src/sources/rules.ts
export type SourceCategory = 'own' | 'competitor' | 'media' | 'community' | 'marketplace' | 'public' | 'other' | 'unknown';

/**
 * 등록 도메인 → 출처 분류 사전.
 * DB CHECK: own|competitor|media|community|marketplace|public|other|unknown
 * (자사·경쟁사 도메인은 classifySource에서 사전보다 먼저 판정)
 */
export const DOMAIN_CATEGORY_RULES: Readonly<Record<string, SourceCategory>> = {
  // 미디어: 영상·뉴스·블로그 플랫폼·포털 콘텐츠
  'youtube.com': 'media',
  'vimeo.com': 'media',
  'twitch.tv': 'media',
  'tiktok.com': 'media',
  'tistory.com': 'media',
  'medium.com': 'media',
  'substack.com': 'media',
  'wordpress.com': 'media',
  'blogspot.com': 'media',
  'velog.io': 'media',
  'brunch.co.kr': 'media',
  'yonhapnews.co.kr': 'media',
  'chosun.com': 'media',
  'joongang.co.kr': 'media',
  'donga.com': 'media',
  'hankyung.com': 'media',
  'mk.co.kr': 'media',
  'sedaily.com': 'media',
  'zdnet.co.kr': 'media',
  'etnews.com': 'media',
  'theverge.com': 'media',
  'techcrunch.com': 'media',
  'nytimes.com': 'media',
  'bbc.com': 'media',
  'reuters.com': 'media',
  'bloomberg.com': 'media',
  'wsj.com': 'media',
  'forbes.com': 'media',
  // 커뮤니티: 포럼·UGC·소셜·리뷰 플랫폼
  'reddit.com': 'community',
  'quora.com': 'community',
  'stackoverflow.com': 'community',
  'stackexchange.com': 'community',
  'dcinside.com': 'community',
  'fmkorea.com': 'community',
  'theqoo.net': 'community',
  'clien.net': 'community',
  'blind.com': 'community',
  'teamblind.com': 'community',
  'inven.co.kr': 'community',
  'ruliweb.com': 'community',
  'instagram.com': 'community',
  'facebook.com': 'community',
  'x.com': 'community',
  'twitter.com': 'community',
  'threads.net': 'community',
  'linkedin.com': 'community',
  'pinterest.com': 'community',
  'discord.com': 'community',
  'telegram.org': 'community',
  'band.us': 'community',
  'g2.com': 'community',
  'capterra.com': 'community',
  'trustpilot.com': 'community',
  'getapp.com': 'community',
  'producthunt.com': 'community',
  'yelp.com': 'community',
  'tripadvisor.com': 'community',
  'github.com': 'community',
  // 마켓플레이스
  'gmarket.co.kr': 'marketplace',
  'coupang.com': 'marketplace',
  'amazon.com': 'marketplace',
  '11st.co.kr': 'marketplace',
  'auction.co.kr': 'marketplace',
  'ebay.com': 'marketplace',
  'etsy.com': 'marketplace',
  // 공공·백과
  'wikipedia.org': 'public',
  'namu.wiki': 'public',
  'britannica.com': 'public',
  'go.kr': 'public',
  'data.go.kr': 'public',
};

/** 서브도메인으로 세분류되는 도메인 */
export const SUBDOMAIN_CATEGORY_RULES: Readonly<Record<string, SourceCategory>> = {
  'blog.naver.com': 'media',
  'post.naver.com': 'media',
  'news.naver.com': 'media',
  'smartstore.naver.com': 'marketplace',
  'shopping.naver.com': 'marketplace',
  'kin.naver.com': 'community',
  'cafe.naver.com': 'community',
  'terms.naver.com': 'public',
  'developer.mozilla.org': 'media',
  'learn.microsoft.com': 'media',
  'developer.android.com': 'media',
  'developer.apple.com': 'media',
};
